Fix integrations tests: passed 9/10
FAILURE ON native-test-libc
Rust is on panic but it is not a segmentation fault !
panicked at 'unsafe precondition(s) violated: slice::get_unchecked_mut requires that the index is within the slice', /home/mordak/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:126:5
21 : rust_begin_unwind, eip=C0347311
73 : _ZN4core9panicking18panic_nounwind_fmt17h5ba92e7d8d33b2eeE, eip=C05A9093
5F : _ZN4core9panicking14panic_nounwind17h4e4f77df2c4a6936E, eip=C05A916F
BB : _ZN75_$LT$usize$u20$as$u20$core..slice..index..SliceIndex$LT$$u5b$T$u5d$$GT$$GT$17get_unchecked_mut17h8fd2a23a25db3e67E, eip=C05077AB
32 : _ZN4core5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$17get_unchecked_mut17hdc555a2bc9d36327E, eip=C0438F02
FE : _ZN20fallible_collections5btree4node123NodeRef$LT$fallible_collections..btree..node..marker..Mut$C$K$C$V$C$fallible_collections..btree..node..marker..Internal$GT$4push17h5e93ef69459934f3E, eip=C03D0D3E